### ISSUE TITLE
Servers get overwritten if they have the same description

### ISSUE THREAD

**Issue by Brueggus** [iandk/servermanager#1]
If two servers are added with the same Description, the first one gets quietly overwritten when the second one is saved.

Would it be possible to index servers by a random id instead?

**Comment by iandk** [comment]
That's right.

Since the application is using plain .json files for storage it was easier to work with the description as the identifier than an ID.
I'll add it to the todo list

**Comment by iandk** [comment]
Added in https://github.com/iandk/servermanager/commit/08463cb4872af746d9ce82cdc121d0c6e9992ae8
 
 Unfortunately, you have to delete the existing data and add your hosts again.
 I might add an update feature at some point.
 
 Edit: If an update doesn't change any core functionality you can just move the /data folder to the new version
