### ISSUE TITLE
Sort- and Linkfeatures

### ISSUE THREAD

**Issue by smilebasti** [iandk/servermanager#11]
I tested the software and it works good.

This is not a Bug but some nice-to-have features would be:

- sorting the list by category like location or OS.
- As the Hostname is already displayed maybe us it as a Link to take you to that host.

**Comment by iandk** [comment]
The sorting feature is on the to-do list.

Using the hostname as a link is a great idea!

**Comment by Brueggus** [comment]
I'm looking into this

**Comment by iandk** [comment]
Added, thanks @Brueggus

**Comment by smilebasti** [comment]
Wow, thank you.

To update just replace the Public folder and keep the old Data folder?

edit: Just saw it in the first issue
