### ISSUE TITLE
Listserver not found

### ISSUE THREAD

**Issue by smilebasti** [iandk/servermanager#8]
Hi, i just tried to install. The page loads, but it tries to connect to .../api/listserver but only gets 404. 
![image](https://user-images.githubusercontent.com/60941345/109331014-9bbb4d80-785c-11eb-8a27-54b4f709d35a.png)
I just copied the Public folder and pointed the Apache server to there.

**Comment by Brueggus** [comment]
Could you check if mod_rewrite is enabled in your Apache config?

**Comment by iandk** [comment]
Also, make sure that you have copied the .htaccess as well. 
The file is hidden, so you might have missed this one.

**Comment by smilebasti** [comment]
Thanks. 

It was both and i had to add AllowOverride All to my site.conf.
Git clone didn't get the .htaccess file.
